import { IconType } from "react-icons";

import {
  HiOutlineRocketLaunch,
  HiOutlineHome,
  HiOutlineKey,
  HiOutlineSquares2X2,
  HiOutlineClock,
  HiOutlineSparkles,
  HiOutlineChatBubbleLeftRight,
  HiOutlineLightBulb,
  HiOutlineCog6Tooth,
  HiOutlineVideoCamera,
  HiOutlinePaintBrush,
  HiOutlineCodeBracket,
  HiOutlineArrowTrendingUp,
  HiOutlineBookOpen,
  HiOutlineUsers,
  HiOutlineCheckCircle,
  HiOutlineDevicePhoneMobile,
  HiOutlineShieldCheck,
  HiOutlineBolt,
  HiOutlineDocumentText,
  HiOutlinePhoto,
  HiOutlineFilm,
  HiOutlineCube,
  HiOutlineChartBar,
  HiOutlineStar,
  HiOutlineSquare3Stack3D,
  HiOutlineGlobeAlt,
  HiOutlineLanguage,
} from "react-icons/hi2";

import {
  BiCircle,
} from "react-icons/bi";

export const iconLibrary: Record<string, IconType> = {
  rocket: HiOutlineRocketLaunch,
  home: HiOutlineHome,
  key: HiOutlineKey,
  layers: HiOutlineSquares2X2,
  clock: HiOutlineClock,
  wand: HiOutlineSparkles,
  sparkles: HiOutlineSparkles,
  messageCircle: HiOutlineChatBubbleLeftRight,
  lightbulb: HiOutlineLightBulb,
  settings: HiOutlineCog6Tooth,
  video: HiOutlineVideoCamera,
  palette: HiOutlinePaintBrush,
  code: HiOutlineCodeBracket,
  trendingUp: HiOutlineArrowTrendingUp,
  bookOpen: HiOutlineBookOpen,
  users: HiOutlineUsers,
  check: HiOutlineCheckCircle,
  laptop: HiOutlineDevicePhoneMobile,
  shield: HiOutlineShieldCheck,
  zap: HiOutlineBolt,
  info: HiOutlineLightBulb,
  download: HiOutlineRocketLaunch,
  type: HiOutlineDocumentText,
  image: HiOutlinePhoto,
  film: HiOutlineFilm,
  box: HiOutlineCube,
  pentagon: HiOutlineSquare3Stack3D,
  barChart: HiOutlineChartBar,
  star: HiOutlineStar,
  circle: BiCircle,
  globe: HiOutlineGlobeAlt,
  language: HiOutlineLanguage,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
